### ISSUE TITLE
Webservice-TC / Request Quotation Method

### ISSUE THREAD

**Issue by byenidogan** [victorlap/BPIL-Protocol-TC-DC#3]
Size (Long)
Arrival (Long)
OrderAwarded (Long)

what do these variables mean?

Size, should differ for different goods so it should be a sequence of goods which include information, height, width, length, weight.

I assume Arrival is preferred arrival time, if thats the case then it should be in date/time format.

And why would you have OrderAwarded in the Request Quotation Method and why would it be in long type?

**Comment by victorlap** [comment]
To browse a version of the protocol with comments see: https://github.com/victorlap/BPIL-Protocol-TC-DC/tree/addff9e80f9c3df6ae2308386aa15c5e01160c8f

We calculate size in pallets, so everyone can calculate that himselves.

OrderAwarded is a timestamp with a deadline for when the quote should be received.
