### ISSUE TITLE
Awarding Contract?

### ISSUE THREAD

**Issue by robertorgarcia** [victorlap/BPIL-Protocol-TC-DC#5]
hello everyone,
reading on the flow of things between TC and DC I believe we're missing a final step.
That of the DC notifying 1 specific TC that they have been awarded the contract, resulting in the truck being sent and finally the NotifyTruckArrival webservice invokation

or am I misreading things?

**Comment by victorlap** [comment]
Hi @robertorgarcia 

That is the AwardOrder request.
